#
# Automations
#
# https://www.home-assistant.io/docs/automation/
#

# This file is used by automation editor in the UI.
# However, it's helpful to test some simple automations in there.
#
# automations.yaml file in the root exists for editor to work.
automation: !include ../automations.yaml

# My automations are stored in automations folder.
automation split: !include_dir_merge_list ../automations