#
# Binary Sensor
#
# https://www.home-assistant.io/integrations/binary_sensor/
#

binary_sensor:
  # Car Wash
  - platform: car_wash
    weather: weather.forecast_nyvky
  # Winter Tires
  - platform: snowtire
    weather: weather.forecast_nyvky
  # Fayna Town Electricity
  - platform: rest
    name: Fayna Electricity
    resource: https://light.fayna.town
    device_class: power
    scan_interval: 60
    value_template: "{{ 'Шось темно' not in value and 'Світла нема' not in value }}"
