#
# Sensor
#
# https://www.home-assistant.io/integrations/sensor/
#

sensor:
  # Electricity Outages Stats
  - platform: history_stats
    unique_id: no_electricity_today
    name: No Electricity Today
    entity_id: binary_sensor.electricity
    state: 'off'
    type: time
    end: '{{ now() }}'
    duration:
      hours: 24
  - platform: history_stats
    unique_id: no_electricity_today_percent
    name: No Electricity Today Percent
    entity_id: binary_sensor.electricity
    state: 'off'
    type: ratio
    end: '{{ now() }}'
    duration:
      hours: 24
