#
# Sensor
#
# https://www.home-assistant.io/integrations/sensor/
#

sensor:
  # System Monitor
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use_percent
        arg: /media
      - type: processor_use
      - type: memory_use_percent
      - type: processor_temperature

  # Lun Misto
  - platform: rest
    name: Misto Lun
    resource: https://api.meteostation.online/chrome/addon/informer/
    value_template: 'OK'
    scan_interval: 300 # every 5 minutes
    json_attributes:
      - lunmisto_air
      - tomtom_jams
      - tomtom_temp

  # Lun Misto AQI
  - platform: rest
    name: Outdoor AQI
    unit_of_measurement: 'AQI'
    device_class: aqi
    resource: https://misto.lun.ua/api/air/v1/public/data/
    value_template: >-
      {% set station = '125' %}
      {# #}
      {% macro aqi(aqihigh, aqilow, conchigh, conclow, conc) -%}
        {{ (aqilow + (conc - conclow) * (aqihigh - aqilow) / (conchigh - conclow)) | round }}
      {%- endmacro %}
      {# #}
      {% for data in value_json %}
        {% if data.station.name == station %}
          {% set conc = data.particles[2].pm25 %}
          {% if conc >= 0 and conc < 12 %}
              {{ aqi(50, 0, 12, 0, conc) }}
          {% elif conc >= 12 and conc < 35.5 %}
              {{ aqi(100, 51, 35.5, 12, conc) }}
          {% elif conc >= 35.5 and conc < 55.5 %}
              {{ aqi(150, 101, 55.5, 35.5, conc) }}
          {% elif conc >= 55.5 and conc < 150 %}
              {{ aqi(200, 151, 150.5, 55.5, conc) }}
          {% elif conc >= 150 and conc < 250.5 %}
              {{ aqi(300, 201, 250.5, 150.5, conc) }}
          {% elif conc >= 250.5 and conc < 350.5 %}
              {{ aqi(400, 301, 350.5, 250.5, conc) }}
          {% elif conc >= 350.5 and conc < 500.5 %}
              {{ aqi(500, 401, 500.5, 350.5, conc) }}
          {% else %}
              unknown
          {% endif %}
        {% endif %}
      {% endfor %}
    scan_interval: 300 # every 5 minutes
    json_attributes_path: "$.[?(@.station.name=='125')].particles[2]"
    json_attributes:
      - pm25
      - pm10
      - pm100
