# https://pre-commit.com/

fail_fast: true
exclude: custom_components
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.0'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.3.0'
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-symlinks
      - id: detect-private-key
  - repo: local
    hooks:
      - id: update-readme
        name: Update README.md
        entry: python helpers/update_readme.py
        language: python
        files: ^automations\.yaml$
        additional_dependencies: [pyyaml]
