#
# Welcome to my Home Assistant configuration!
#
# This file is only used to bootstrap the system.
# You can find the rest of the configurationo inside the integrations folder.
#

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Load Home Assistant integrations as packages
homeassistant:
  # Load customizations
  # Only for those device that are not customisable from UI
  customize: !include customize.yaml
  # Load packages
  packages: !include_dir_named integrations

shell_command:
  docker_restart: >
    ssh
    -i /config/.ssh/id_rsa
    -o 'StrictHostKeyChecking=no'
    ubuntu@192.168.50.113 '~/smart-home/scripts/docker-restart.sh'
  docker_update: >
    ssh
    -i /config/.ssh/id_rsa
    -o 'StrictHostKeyChecking=no'
    ubuntu@192.168.50.113 '~/smart-home/scripts/docker-update.sh'
