# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Kyiv Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  time_zone: Europe/Kiev #KyivNotKiev
  unit_system: metric
  # Load customizations
  # Only for those device that are not customisable from UI
  customize: !include_dir_merge_named customizations
  # Load packages
  packages: !include_dir_named integrations
  external_url: !secret external_url
  internal_url: !secret internal_url
