homeassistant: true
devices: devices.yaml
groups: groups.yaml
advanced:
  channel: 15
  last_seen: ISO_8601_local
  log_level: warn
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
availability:
  active:
    timeout: 10
  passive:
    timeout: 720
